In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def importImage(dir):
    
    im_array = plt.imread("wallpaper.png")
    im_array = (im_array * 255).astype(int)

    height = np.shape(im_array)[0]
    width = np.shape(im_array)[1]
    
    channels = np.shape(im_array)[2]
    
    return im_array, width, height, channels

In [3]:
image_dir = "./rgb.png"
original, width, height, channels = importImage(image_dir)
original = original[:,:,:3]
print("image : ", np.shape(original))

image :  (922, 1920, 3)


In [4]:
def euclidDist(point1, point2):
    ss = 0
    for i, j in zip(point1, point2):
        ss += np.power( (i-j), 2 )
        
    return np.sqrt(ss)

In [5]:
def getClosest(point, array):
    dists = []
    for target in array:
        dists.append( euclidDist(point, target) )
    closest_index = np.argmin(dists)
    return array[closest_index]

In [6]:
def createMeans(image, k):
    means = []
    for i in range(k):
        yy = np.random.randint(0, height)
        xx = np.random.randint(0, width)
        means.append( image[yy,xx,:] )
    return np.asarray(means)

In [7]:
def getClusters(original, means):
    clusters = np.zeros(np.shape(original), dtype=int)
    
    for yy in range(height):
        for xx in range(width):
            clusters[yy, xx] = getClosest(original[yy, xx], means)
            
    return clusters

In [8]:
def getMeans(current, original, means):
    new_means = []
    for centroid in means:
        
        summ = np.zeros(3, dtype=int)
        count = 0
        for cur_yy, or_yy in zip(current, original):
            for cur_xx, or_xx in zip(cur_yy, or_yy):
                if (cur_xx == centroid).all():
                    summ += or_xx
                    count += 1
        
        new_means.append( (summ/count).astype(int) )
        
    return np.asarray(new_means)

In [ ]:
k = 3
print("k = ", k, "\n")

means = createMeans(original, k)
#means = np.array([[255, 0, 0], [0, 255, 0], [0, 0, 255], [255, 255, 0]])
print("means ;", np.shape(means), ";", type(means))
print(means, "\n")

max_iterations = 5
i = 0
while i < max_iterations:
    print("iter :", i)
    current = getClusters(original, means)
    
    means = getMeans(current, original, means)
    i += 1

k =  3 

means ; (3, 3) ; <class 'numpy.ndarray'>
[[ 30  29  35]
 [150 179 113]
 [ 84 102 122]] 

iter : 0


In [ ]:
f, (ax1, ax2) = plt.subplots(1, 2, figsize = (10, 5))
ax1.imshow((original/255), aspect = "equal" )
ax2.imshow((current/255), aspect = "equal")

In [ ]:
fig = plt.figure(frameon=False)

ax = plt.Axes(fig, [0., 0., 1., 1.])
ax.set_axis_off()
fig.add_axes(ax)

ax.imshow((current/255), aspect='equal')
fig.savefig("wallpaper-clusters.png")